/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-05-02 23:18:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Zatonio/Desktop/Instituto%20DAW/2º%20DAW/PI/Proyecto/PI/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343812618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1682964975242L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"boostrap/bootstrap-5.0.2-dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("        <script src=\"boostrap/bootstrap-5.0.2-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\" integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\" crossorigin=\"anonymous\"></script>  \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <title>Second Weapon Life </title>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <header class=\" text-white\" >\r\n");
      out.write("            <div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start w-100 \"id=\"cabecera\" id=\"cabecera\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0\">\r\n");
      out.write("                        <li><a href=\"./Inicio\" class=\"nav-link px-2 text-secondary\"><img src=\"img/LogoSWL.png\" alt=\"LogoSWL\" width=\"100px\" height=\"40px\" ></a></li>\r\n");
      out.write("                        <li><a href=\"./SobreNosotros\" class=\"nav-link px-2 text-white mt-2 elementosNoResponsive\">Sobre Nosotros</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"nav-link px-2 text-white mt-2 elementosNoResponsive\" >Como Trabajamos</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"nav-link px-2 text-white mt-2 elementosNoResponsive\">Foro</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"nav-link px-2 text-white mt-2 elementosNoResponsive\" >Encuentranos</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <form class=\"col-12 col-lg-auto mb-3 mb-lg-0 me-lg-5 elementosNoResponsive\" >\r\n");
      out.write("                        <input type=\"search\" class=\"form-control form-control-dark\" placeholder=\"Buscar...\" aria-label=\"Search\">\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"text-end me-5\">\r\n");
      out.write("\r\n");
      out.write("                        <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("                            <div class=\"container-fluid\" id=\"Usuario\">\r\n");
      out.write("\r\n");
      out.write("                                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                                </button>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                                    <li class=\"nav-item dropdown \" id=\"puntoNegro\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <a href=\"sobreNosotros.html\" class=\"nav-link px-2 text-white mt-2 elementosResponsive\">Sobre Nosotros</a>\r\n");
      out.write("\r\n");
      out.write("                                        <a href=\"#\" class=\"nav-link px-2 text-white mt-2 elementosResponsive\" >Como Trabajamos</a>\r\n");
      out.write("                                        <a href=\"#\" class=\"nav-link px-2 text-white mt-2 elementosResponsive\">Foro</a>\r\n");
      out.write("                                        </a>\r\n");
      out.write("\r\n");
      out.write("                                        <a href=\"#\" class=\"nav-link px-2 text-white mt-2 elementosResponsive\">Encuentranos</a>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <main>\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"py-1 text-center container-fluid mt-5\" id=\"slider\">\r\n");
      out.write("\r\n");
      out.write("                            <div id=\"carouselExampleCaptions\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("                                <div class=\"carousel-indicators\">\r\n");
      out.write("                                    <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active \" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("                                    <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("                                    <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"carousel-inner\">\r\n");
      out.write("                                    <div class=\"carousel-item active\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <img src=\"img/slider/descarga.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"carousel-item\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <img src=\"img/slider/images (1).jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"carousel-item\">\r\n");
      out.write("                                        <a href=\"\">\r\n");
      out.write("                                            <img src=\"img/slider/tipos-de-escopetas-3.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("                                    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    <span class=\"visually-hidden\">Anterior</span>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("                                    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    <span class=\"visually-hidden\">Siguiente</span>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"album py-5 bg-dark\">\r\n");
      out.write("                            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3\">\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Escopetas/815983.jpg\" alt=\"\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage1\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Carabinas/355044-scaled.jpg\" alt=\"\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage2\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Pistolas/558885-scaled.jpg\" alt=\"\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage3\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Carabinas/777199-scaled.jpg\" alt=\"\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage4\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Escopetas/969786.jpg\" alt=\"\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage5\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Carabinas/294978.jpeg\"  alt=\"sac\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>  \r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage6\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Pistolas/621321-scaled.jpg\" alt=\"\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage7\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Aire comprimido/pistolas-aire-comprimido-gamo-p-23-combat.jpg\" alt=\"\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage8\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <div class=\"card shadow-sm\">\r\n");
      out.write("                                            <div >\r\n");
      out.write("                                                <img src=\"img/Pistolas/uberti-colt-army-1860.jpg\" alt=\"\" width=\"100%\" height=\"225\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <p class=\"card-text\">\r\n");
      out.write("                                                <div class=\"card\" id=\"NombreAnuncio\">\r\n");
      out.write("                                                    <p>Nombre anuncio</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card\" id=\"CuerpoAnuncio\">\r\n");
      out.write("                                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim laborum molestiae dolor, qui dignissimos officiis officia in omnis fuga quia expedita, vitae rerum fugit necessitatibus impedit animi quidem excepturi incidunt.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                    <div class=\"btn-group\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2 \"data-bs-toggle=\"modal\" data-bs-target=\"#modalImage9\" > Ver el producto </button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-warning  me-2\">Ir al anuncio</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!--Ventana modal-->\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage9\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage9\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Pistolas/uberti-colt-army-1860.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage1\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage1\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Escopetas/815983.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage2\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage2\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Carabinas/355044-scaled.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage3\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage3\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Pistolas/558885-scaled.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage4\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage4\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Carabinas/777199-scaled.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage5\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage5\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Escopetas/969786.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage6\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage6\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Carabinas/294978.jpeg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage7\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage7\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Pistolas/621321-scaled.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div tabindex=\"-1 \" aria-labelledby=\"modalImage8\" aria-hidden=\"true\"\r\n");
      out.write("\r\n");
      out.write("                             class=\"modal fade\" id=\"modalImage8\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <img src=\"img/Aire comprimido/pistolas-aire-comprimido-gamo-p-23-combat.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <footer\r\n");
      out.write("                        class=\"text-center text-lg-start text-white\"\r\n");
      out.write("                        >\r\n");
      out.write("\r\n");
      out.write("                        <!-- Grid container -->\r\n");
      out.write("                        <div class=\"container p-4 pb-0\">\r\n");
      out.write("                            <hr class=\"my-3\">\r\n");
      out.write("                            <!-- Section: Links -->\r\n");
      out.write("                            <section class=\"\">\r\n");
      out.write("                                <!--Grid row-->\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("                                    <div class=\"col-md-3 col-lg-3 col-xl-3 mx-auto mt-3\">\r\n");
      out.write("                                        <h6 class=\"text-uppercase mb-4 font-weight-bold\">\r\n");
      out.write("                                            Second Weapaon Life\r\n");
      out.write("                                        </h6>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            Somos una plataforma, dedicada a facilitar la venta de armas de segunda mano entre propietarios.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("                                    <hr class=\"w-100 clearfix d-md-none\" />\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("                                    <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mt-3\">\r\n");
      out.write("                                        <h6 class=\"text-uppercase mb-4 font-weight-bold\">Tipos de armas</h6>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <a class=\"text-white\">Escopetas</a>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <a class=\"text-white\">Carabinas</a>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <a class=\"text-white\">Aire comprimido</a>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <a class=\"text-white\">Pistolas</a>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("                                    <hr class=\"w-100 clearfix d-md-none\" />\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("                                    <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mt-3\">\r\n");
      out.write("                                        <h6 class=\"text-uppercase mb-4 font-weight-bold\">\r\n");
      out.write("                                            Enlaces de Interes\r\n");
      out.write("                                        </h6>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <a class=\"text-white\" href=\"GestionCuenta.html\">Ir a tu cuenta</a>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <a class=\"text-white\" href=\"registro\">Registrate</a>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <a class=\"text-white\">Anuncios</a>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <a class=\"text-white\" href=\"sobreNosotros.html\">Sobre nosotros</a>\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("                                    <hr class=\"w-100 clearfix d-md-none\" />\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("                                    <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mt-3\">\r\n");
      out.write("                                        <h6 class=\"text-uppercase mb-4 font-weight-bold\">Contacto</h6>\r\n");
      out.write("                                        <p><i class=\"fas fa-home mr-3\"></i>Bollullos de la Mitación, CP 41110 (Sevilla)</p>\r\n");
      out.write("                                        <p><i class=\"fas fa-envelope mr-3\"></i> info@swl.es</p>\r\n");
      out.write("                                        <p><i class=\"fas fa-phone mr-3\"></i><a class=\"text-white\" href=tel:+34607450598>Llamanos </a> </p>\r\n");
      out.write("                                        <p><i class=\"fas fa-print mr-3\"></i> <a href=\"8VR5+GX Bollullos de la Mitación\"></a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--Grid row-->\r\n");
      out.write("                            </section>\r\n");
      out.write("                            <!-- Section: Links -->\r\n");
      out.write("\r\n");
      out.write("                            <hr class=\"my-3\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- Section: Copyright -->\r\n");
      out.write("                            <section class=\"p-3 pt-0\">\r\n");
      out.write("                                <div class=\"row d-flex align-items-center\">\r\n");
      out.write("                                    <!-- Grid column -->\r\n");
      out.write("                                    <div class=\"col-md-7 col-lg-8 text-center text-md-start\">\r\n");
      out.write("                                        <!-- Copyright -->\r\n");
      out.write("                                        <div class=\"p-3\">\r\n");
      out.write("                                            © José Antonio López López \r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!-- Copyright -->\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-md-5 col-lg-4 ml-lg-0 text-center text-md-end\">\r\n");
      out.write("                                        <a href=\"https://facebook.com\"\r\n");
      out.write("                                           class=\"btn btn-outline-light btn-floating m-1\"\r\n");
      out.write("                                           class=\"text-white\"\r\n");
      out.write("                                           role=\"button\"\r\n");
      out.write("                                           ><i class=\"fab fa-facebook-f\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-facebook\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                <path d=\"M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z\"/>\r\n");
      out.write("                                                </svg></i\r\n");
      out.write("                                            ></a>\r\n");
      out.write("\r\n");
      out.write("                                        <a href=\"https://twitter.com\"\r\n");
      out.write("                                           class=\"btn btn-outline-light btn-floating m-1\"\r\n");
      out.write("                                           class=\"text-white\"\r\n");
      out.write("                                           role=\"button\"\r\n");
      out.write("                                           ><i class=\"fab fa-twitter\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-twitter\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                <path d=\"M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z\"/>\r\n");
      out.write("                                                </svg>  </i\r\n");
      out.write("                                            ></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <a href=\"https://www.google.com/maps/place/C.+Granada,+13,+41110+Bollullos+de+la+Mitaci%C3%B3n,+Sevilla/@37.3413656,-6.142208,17z/data=!4m6!3m5!1s0xd121230798e25eb:0x59f66d5498776f7c!8m2!3d37.3413656!4d-6.1400193!16s%2Fg%2F11c227sx43\"\r\n");
      out.write("                                           class=\"btn btn-outline-light btn-floating m-1\"\r\n");
      out.write("                                           class=\"text-white\"\r\n");
      out.write("                                           role=\"button\"\r\n");
      out.write("                                           ><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-geo-alt\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                            <path d=\"M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z\"/>\r\n");
      out.write("                                            <path d=\"M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z\"/>\r\n");
      out.write("                                            </svg></a>\r\n");
      out.write("                                        <a href=\"https://wa.me/+34607450598\"\r\n");
      out.write("                                           class=\"btn btn-outline-light btn-floating m-1\"\r\n");
      out.write("                                           class=\"text-white\"\r\n");
      out.write("                                           role=\"button\"\r\n");
      out.write("                                           ><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-whatsapp\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                            <path d=\"M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z\"/>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <a href=\"https://Instagram.com\"\r\n");
      out.write("                                           class=\"btn btn-outline-light btn-floating m-1\"\r\n");
      out.write("                                           class=\"text-white\"\r\n");
      out.write("                                           role=\"button\"\r\n");
      out.write("                                           ><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-instagram\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                            <path d=\"M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z\"/>\r\n");
      out.write("                                            </svg></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </section>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </body>\r\n");
      out.write("                    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(63,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.id_usuario==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("                                            <a href=\"#\" class=\"nav-link px-2 text-white mt-2 elementosResponsive\"><button type=\"button\" class=\"btn btn-outline-warning  me-2\"><a href=\"./Login\" id=\"login\"> Iniciar sesión</a></button></a>\r\n");
          out.write("\r\n");
          out.write("                                            </a>\r\n");
          out.write("\r\n");
          out.write("                                            <a href=\"#\" class=\"nav-link px-2 text-white mt-2 elementosResponsive\"><button type=\"button\" class=\"btn btn-outline-warning me-2\" > <a href=\"./Registro\" id=\"login\"> Registrate</a></button>\r\n");
          out.write("                                            </a>\r\n");
          out.write("\r\n");
          out.write("                                            </a>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /index.jsp(74,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.id_usuario!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDarkDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
          out.write("                                                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                            </a>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("                                            <ul class=\"dropdown-menu-dark  dropdown-menu  \"  aria-labelledby=\"navbarDarkDropdownMenuLink \" >\r\n");
          out.write("\r\n");
          out.write("                                                ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("                                                ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("                                                <li><a class=\"dropdown-item\" href=\"#\"> <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-bag-fill\" viewBox=\"0 0 16 16\">\r\n");
          out.write("                                                        <path d=\"M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5z\"/>\r\n");
          out.write("                                                        </svg> Compras</a></li>\r\n");
          out.write("                                                <li><a class=\"dropdown-item\" href=\"#\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-box-seam-fill\" viewBox=\"0 0 16 16\">\r\n");
          out.write("                                                        <path fill-rule=\"evenodd\" d=\"M15.528 2.973a.75.75 0 0 1 .472.696v8.662a.75.75 0 0 1-.472.696l-7.25 2.9a.75.75 0 0 1-.557 0l-7.25-2.9A.75.75 0 0 1 0 12.331V3.669a.75.75 0 0 1 .471-.696L7.443.184l.01-.003.268-.108a.75.75 0 0 1 .558 0l.269.108.01.003 6.97 2.789ZM10.404 2 4.25 4.461 1.846 3.5 1 3.839v.4l6.5 2.6v7.922l.5.2.5-.2V6.84l6.5-2.6v-.4l-.846-.339L8 5.961 5.596 5l6.154-2.461L10.404 2Z\"/>\r\n");
          out.write("                                                        </svg> Ventas</a></li>\r\n");
          out.write("\r\n");
          out.write("                                                <li><a class=\"dropdown-item\" href=\"#\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-calendar4\" viewBox=\"0 0 16 16\">\r\n");
          out.write("                                                        <path d=\"M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM2 2a1 1 0 0 0-1 1v1h14V3a1 1 0 0 0-1-1H2zm13 3H1v9a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V5z\"/>\r\n");
          out.write("                                                        </svg> Mis anuncios</a></li>\r\n");
          out.write("\r\n");
          out.write("                                                <li><a class=\"dropdown-item\" href=\"usuario/GestionarPerfil\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-person-circle\" viewBox=\"0 0 16 16\">\r\n");
          out.write("                                                        <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\"/>\r\n");
          out.write("                                                        <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\"/>\r\n");
          out.write("                                                        </svg> Gestionar Perfil</a></li>\r\n");
          out.write("                                                <li><a class=\"dropdown-item\" href=\"./CerrarSesion\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-box-arrow-in-right\" viewBox=\"0 0 16 16\">\r\n");
          out.write("                                                        <path fill-rule=\"evenodd\" d=\"M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z\"/>\r\n");
          out.write("                                                        <path fill-rule=\"evenodd\" d=\"M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z\"/>\r\n");
          out.write("                                                        </svg> Cerrar Sesión </a></li>\r\n");
          out.write("                                            </ul>\r\n");
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /index.jsp(83,48) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.rol=='admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                    <li><a class=\"dropdown-item\" href=\"admin/PanelAdministracion\"> <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-pc-display-horizontal\" viewBox=\"0 0 16 16\">\r\n");
          out.write("                                                            <path d=\"M1.5 0A1.5 1.5 0 0 0 0 1.5v7A1.5 1.5 0 0 0 1.5 10H6v1H1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-5v-1h4.5A1.5 1.5 0 0 0 16 8.5v-7A1.5 1.5 0 0 0 14.5 0h-13Zm0 1h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5ZM12 12.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Zm2 0a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0ZM1.5 12h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1ZM1 14.25a.25.25 0 0 1 .25-.25h5.5a.25.25 0 1 1 0 .5h-5.5a.25.25 0 0 1-.25-.25Z\"/>\r\n");
          out.write("                                                            </svg> Panel de Administración</a></li>\r\n");
          out.write("                                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /index.jsp(89,48) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.rol=='moderador'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                    <li><a class=\"dropdown-item\" href=\"moderador/PanelModeracion\"> <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-pc-display-horizontal\" viewBox=\"0 0 16 16\">\r\n");
          out.write("                                                            <path d=\"M1.5 0A1.5 1.5 0 0 0 0 1.5v7A1.5 1.5 0 0 0 1.5 10H6v1H1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-5v-1h4.5A1.5 1.5 0 0 0 16 8.5v-7A1.5 1.5 0 0 0 14.5 0h-13Zm0 1h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5ZM12 12.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Zm2 0a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0ZM1.5 12h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1ZM1 14.25a.25.25 0 0 1 .25-.25h5.5a.25.25 0 1 1 0 .5h-5.5a.25.25 0 0 1-.25-.25Z\"/>\r\n");
          out.write("                                                            </svg> Panel de Moderación</a></li>\r\n");
          out.write("                                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
